language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_ENV=esp12e
  - PLATFORMIO_ENV=nodemcuv2

install:
  # PlatformIO
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  # copy password file
  - cp src/config.h-example src/config.h
  - platformio lib install

script:
  - platformio run --environment=$PLATFORMIO_ENV
